# Generated by Django 4.1 on 2022-11-10 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='subgroup',
            field=models.CharField(choices=[('A1', '≥ 230 kV'), ('A2', 'de 88 kV a 138 kV'), ('A3', 'de 69 kV'), ('A3a', 'de 30 kV a 44 kV'), ('A4', 'de 2,3 kV a 25 kV'), ('AS', '< a 2,3 kV, a partir de sistema subterrâneo de distribuição')], default='A3', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='tariff',
            unique_together={('subgroup', 'distributor')},
        ),
    ]
