# Generated by Django 4.1 on 2022-11-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0002_tariff_subgroup_alter_tariff_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tariff',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tariff',
            name='flag',
            field=models.CharField(choices=[('B', 'Azul'), ('G', 'Verde')], default='B', max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='tariff',
            unique_together={('subgroup', 'distributor', 'flag')},
        ),
    ]
