# Generated by Django 4.1 on 2022-12-13 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0005_distributor_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='distributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='tariffs.distributor'),
        ),
    ]
