# Generated by Django 4.1 on 2022-12-14 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_merge_20221025_0920'),
        ('tariffs', '0006_alter_tariff_distributor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='cnpj',
            field=models.CharField(help_text='14 números sem caracteres especiais', max_length=14, verbose_name='CNPJ'),
        ),
        migrations.AlterUniqueTogether(
            name='distributor',
            unique_together={('university', 'cnpj')},
        ),
    ]
