# Generated by Django 4.1 on 2022-10-28 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_merge_20221025_0920'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universityuser',
            name='favorite_consumer_units',
            field=models.ManyToManyField(blank=True, to='universities.consumerunit'),
        ),
    ]
