# Generated by Django 4.1 on 2022-12-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_universityuser_favorite_consumer_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='type',
            field=models.CharField(max_length=25),
            preserve_default=False,
        ),
    ]
