# Generated by Django 4.1 on 2023-03-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('super_user', 'super_user'), ('super_user', 'university_admin'), ('super_user', 'university_user')], editable=False, max_length=25),
        ),
    ]
