# Generated by Django 4.1 on 2022-10-18 23:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today, unique=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('tariff_flag', models.CharField(blank=True, choices=[('V', 'Verde'), ('A', 'Azul')], max_length=1, null=True)),
                ('subgroup', models.CharField(blank=True, choices=[('A1', '≥ 230 kV'), ('A2', 'de 88 kV a 138 kV'), ('A3', 'de 69 kV'), ('A3a', 'de 30 kV a 44 kV'), ('A4', 'de 2,3 kV a 25 kV'), ('AS', '< a 2,3 kV, a partir de sistema subterrâneo de distribuição')], max_length=3, null=True)),
                ('supply_voltage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('peak_contracted_demand_in_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('off_peak_contracted_demand_in_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnergyBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('invoice_in_reais', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_atypical', models.BooleanField(default=False)),
                ('peak_consumption_in_kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('off_peak_consumption_in_kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('peak_measured_demand_in_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('off_peak_measured_demand_in_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contracts.contract')),
            ],
        ),
    ]
