# Generated by Django 4.1 on 2022-10-26 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_merge_20221025_0920'),
        ('contracts', '0002_contract_consumer_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='energybill',
            name='consumer_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='universities.consumerunit'),
            preserve_default=False,
        ),
    ]
