# Generated by Django 4.1 on 2022-11-08 23:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_energybill_consumer_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
