# Generated by Django 4.1 on 2022-11-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_alter_contract_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='supply_voltage',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
