# Generated by Django 4.1 on 2022-11-28 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0005_distributor_is_active'),
        ('contracts', '0006_alter_contract_subgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='distributor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tariffs.distributor'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='tariff_flag',
            field=models.CharField(blank=True, choices=[('G', 'Verde'), ('B', 'Azul')], max_length=1, null=True),
        ),
    ]
