# Generated by Django 4.1 on 2023-05-18 14:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0009_alter_contract_distributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='energybill',
            name='energy_bill_file',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'ppt', 'xlsx', 'png', 'jpg', 'jpeg'])]),
        ),
    ]
