# Generated by Django 4.1 on 2022-10-06 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome da Unidade Consumidora. Ex: Darcy Ribeiro', max_length=50, unique=True, verbose_name='Nome')),
                ('code', models.CharField(help_text='Cheque a conta de luz para obter o código da Unidade Consumidora. Insira apenas números', max_length=15, unique=True, verbose_name='Código da Unidade Consumidora')),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('university', models.ForeignKey(help_text='Uma Unidade Consumidora deve estar ligada a uma Universidade', on_delete=django.db.models.deletion.PROTECT, to='universities.university', verbose_name='Universidade')),
            ],
        ),
    ]
