# Generated by Django 4.1 on 2022-10-24 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_consumerunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerunit',
            name='university',
            field=models.ForeignKey(help_text='Uma Unidade Consumidora deve estar ligada a uma Universidade', on_delete=django.db.models.deletion.PROTECT, related_name='consumer_units', to='universities.university', verbose_name='Universidade'),
        ),
    ]
