# Generated by Django 4.1 on 2022-10-19 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_consumerunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='acronym',
            field=models.CharField(help_text='Exemplo: UnB, UFSC, UFB', max_length=50, null=True, unique=True, verbose_name='Sigla'),
        ),
    ]
