# Generated by Django 4.1 on 2022-10-25 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_alter_consumerunit_university'),
        ('universities', '0003_university_acronym'),
    ]

    operations = [
    ]
