# Generated by Django 4.1 on 2022-12-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_merge_20221025_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consumerunit',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
