# Generated by Django 4.1 on 2022-12-21 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0005_university_created_on_alter_consumerunit_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
