# Generated by Django 4.1 on 2023-05-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0006_alter_university_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
